config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'

  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'logout', to: 'sessions#destroy'
  
  resources :surveys
  # post 'edit', to: 'surveys#edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/survey.rb
class Survey < ApplicationRecord
    belongs_to :user, required: true

    validates :title, presence: true
    validates :questions, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :surveys

    validates :username, presence: true, uniqueness: true
    validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?

    def current_user    
        User.find_by(id: session[:user_id])  
    end

    def logged_in?
        current_user.present?
    end

    def authorized
        redirect_to '/welcome' unless logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   skip_before_action :authorized, only: [:new, :create, :welcome]
 
   def new
      @user = User.new
   end
 
   def create
     @user = User.find_by(username: params[:username])
 
    if @user && @user.authenticate(params[:password])
       session[:user_id] = @user.id
       redirect_to '/welcome'
    else
       redirect_to '/login'
    end
   end
 
   def destroy
       session[:user_id] = nil
       redirect_to '/login'
   end
 

   def login
      if @user && @user.authenticate(params[:password])
         session[:user_id] = @user.id
         redirect_to '/welcome'
      else
   
         redirect_to '/login'
      end

   end
 
 end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

    def new
        @survey = Survey.new 
    end
    
    def create
        @user = User.find(params.dig(:survey, :user_id))
        @survey = @user.surveys.create(survey_params)
        if @survey.save
            redirect_to survey_path(@survey)
        else 
            render 'new'
        end
    end

    def edit
        @survey = current_user.surveys.find(params[:id])
    end

    def update
        @survey = current_user.surveys.find(params[:id])

        if @survey.update_attributes(survey_params)
          redirect_to survey_path(@survey)
        else
          render 'edit'
        end
      end

    def destroy
        survey = Survey.find(params[:id])
        survey.destroy
        redirect_to surveys_path, notice: "Deleted Survey!"
    end

    def index
        @surveys = current_user.surveys
    end
    
    def show
        @survey = Survey.find(params[:id])
    end

    private
    def survey_params
        params.require(:survey).permit(:title, :questions, :user_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username, :password))
      session[:user_id] = @user.id
      redirect_to '/welcome'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html lang ="en">
  <head>
    <title>Secret Project BRUHH</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  
    <%= yield %>
  </body>
</html>

app/views/surveys/create.html.erb
<%= form_with model: @survey, url: surveys_path do |form| %>

<% if @survey.errors.any? %>

    <div id="error_explanation">
      <h2>
        <%= pluralize(@survey.errors.count, "error") %> prohibited
        this survey from being saved:
      </h2>
      <ul>
        <% @survey.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :questions %><br>
    <%= form.text_area :questions %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/surveys/edit.html.erb
<h1>Edit ya surveysss bruh</h1>

<%= form_with model: @survey, url: survey_path, method: :put do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :questions %><br>
    <%= form.text_area :questions %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/surveys/index.html.erb
<h1>Surveys Y'all</h1>

<% @surveys.each do |survey| %>
<div>
  <ul>
      <%= survey.title %>
      <%= survey.questions %>
      <%= link_to 'Show', survey_path(survey) %>
      <%= link_to 'Edit', edit_survey_path(survey)%>
      <%= link_to 'Delete', survey_path(survey), method: :delete, data: { confirm: "Are you sure?" }%>
   </ul>
  </div>
  <% end %>

<br>
<%= button_to 'New Survey', new_survey_path, method: :get%>
<%= button_to "Back", root_path, method: :get%>

app/views/surveys/new.html.erb
<%= form_with model: @survey, url: surveys_path do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :questions %><br>
    <%= form.text_area :questions %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= button_to "Back", surveys_path, method: :get %>

app/views/surveys/show.html.erb
<h1>Your survey my g</h1>

<h3>Title:</h3>
<h2><%= @survey.title %> </h2>

<h3>Questions:</h3>
<h2><%= @survey.questions %></h2>
<%= link_to "Back", surveys_path %>
<%= link_to "Edit", edit_survey_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%>
  <br>
  <%= f.submit %>
<%end%>